### ISSUE TITLE
关于framework7 + vue 路由切换问题

### ISSUE THREAD

**Issue by chenxu-javascript** [yawuling/vue-framework7#1]
大佬， 请教你一个问题， 最近在看这个项目。  比如说从顶级页面切换到about 页面， 页面是能跳转到， 但是url不变化。这种 有什么处理到办法嘛

**Comment by yawuling** [comment]
在framework7 v1 版本中，是可以在初始化APP的时候加上配置：`pushState`，将它设置为true，url就会变化，这时候的url分隔符默认为 '#!/'，可以修改为：`pushStateSeparator: ''`，这个我刚在项目里加上了，在初始化的注释中。

**Comment by yawuling** [comment]
在framework7 v2 版本中，不再是在初始化APP中进行配置，而是需要在routes中的每个路由中进行配置，地址是：http://framework7.io/docs/routes.html 中的 Route Options。我之前写这个项目的时候还是framework7 v1，现在v2没有去了解过

**Comment by chenxu-javascript** [comment]
感谢大佬提供的解决办法， 在这个issues 下 一下这个问题。 官方文档是说的在routes下面 options ：{ pushState: true } ; 但是这个是不起效的；  在github 上有找到一个解决办法； https://github.com/framework7io/Framework7-Vue/issues/240 ；
