### ISSUE TITLE
可以实现date range吗？

### ISSUE THREAD

**Issue by NickLee380** [yawuling/vue-framework7#2]
framework7好像是有多种calender的，包括时间范围（选开始时间和结束时间）， framework7-vue 也可以使用吗？

**Comment by yawuling** [comment]
> framework7好像是有多种calender的，包括时间范围（选开始时间和结束时间）， framework7-vue 也可以使用吗？

写成vue是可以写，但framework7原本的设计思想就是操作dom，而非操作数据，你放到vue文件中进行dom操作也是可以用calendar的，就是没数据驱动那么好看。我这个工程里面部分组件就是用原本framework7的组件调用方式，framework-vue其实就是在原本的framework7上面包一层
